version = 0.1

[default.deploy.parameters]
stack_name = "email-booking-parse-s3"
resolve_s3 = false
s3_bucket = "email-parse-deployment-bucket-1763335116"
s3_prefix = "email-booking-parse-s3"
region = "us-east-1"
confirm_changeset = false
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "us-east-1"
