/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TravelSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  apiUrl: "",
  apiKey: "",
  tripsFolder: "Decimal System/10-19 Life admin/15 Travel, events, & entertainment \u{1F392}/15.52 Active Trips"
};

// src/settings.ts
var import_obsidian = require("obsidian");
var TravelSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("API URL").setDesc(
      "The base URL of your travel booking API (e.g., https://xxx.execute-api.us-east-1.amazonaws.com)"
    ).addText(
      (text) => text.setPlaceholder("https://your-api-url.com").setValue(this.plugin.settings.apiUrl).onChange(async (value) => {
        this.plugin.settings.apiUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("API key for authenticating requests").addText((text) => {
      text.setPlaceholder("your-api-key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("Trips folder").setDesc(
      "Vault folder where synced trip notes are created. Subfolders per trip are used if they exist."
    ).addText(
      (text) => text.setPlaceholder("path/to/trips").setValue(this.plugin.settings.tripsFolder).onChange(async (value) => {
        this.plugin.settings.tripsFolder = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/sync.ts
var import_obsidian3 = require("obsidian");

// src/api.ts
var import_obsidian2 = require("obsidian");
var TravelApi = class {
  constructor(settings) {
    this.settings = settings;
  }
  async get(path) {
    const url = `${this.settings.apiUrl.replace(/\/$/, "")}${path}`;
    const response = await (0, import_obsidian2.requestUrl)({
      url,
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        ...this.settings.apiKey ? { Authorization: `Bearer ${this.settings.apiKey}` } : {}
      }
    });
    if (response.status !== 200) {
      throw new Error(
        `API request failed: ${response.status} ${response.text}`
      );
    }
    return response.json;
  }
  async listTrips() {
    const data = await this.get("/trips/");
    return data.trips;
  }
  async getTripNote(tripName) {
    return this.get(
      `/export/obsidian/trip-note/${encodeURIComponent(tripName)}`
    );
  }
};

// src/sync.ts
var FRONTMATTER_TYPE = "travel-sync";
var TravelSync = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
    this.api = new TravelApi(settings);
  }
  async syncTrips() {
    if (!this.settings.apiUrl) {
      new import_obsidian3.Notice("Travel Sync: API URL not configured. Check plugin settings.");
      return;
    }
    try {
      const apiTrips = await this.api.listTrips();
      const existingSyncedTrips = await this.getExistingSyncedTrips();
      const tripsToSync = /* @__PURE__ */ new Set([
        ...apiTrips,
        ...existingSyncedTrips.keys()
      ]);
      if (tripsToSync.size === 0) {
        new import_obsidian3.Notice("Travel Sync: No trips to sync.");
        return;
      }
      let synced = 0;
      let errors = 0;
      for (const tripName of tripsToSync) {
        try {
          const tripNote = await this.api.getTripNote(tripName);
          await this.writeTripNote(
            tripName,
            tripNote.filename,
            tripNote.content,
            existingSyncedTrips.get(tripName)
          );
          synced++;
        } catch (e) {
          const msg = e instanceof Error ? e.message : String(e);
          if (!msg.includes("404")) {
            console.error(
              `Travel Sync: Error syncing trip "${tripName}":`,
              e
            );
            errors++;
          }
        }
      }
      const parts = [`Synced ${synced} trip${synced !== 1 ? "s" : ""}`];
      if (errors > 0) {
        parts.push(`${errors} error${errors !== 1 ? "s" : ""}`);
      }
      new import_obsidian3.Notice(`Travel Sync: ${parts.join(", ")}`);
    } catch (e) {
      console.error("Travel Sync: Error during sync:", e);
      new import_obsidian3.Notice(
        "Travel Sync: Failed to connect to API. Check your settings."
      );
    }
  }
  /**
   * Scan the trips folder for existing files with `type: travel-sync` frontmatter.
   * Returns a map of trip name -> file path.
   */
  async getExistingSyncedTrips() {
    var _a;
    const result = /* @__PURE__ */ new Map();
    const folderPath = (0, import_obsidian3.normalizePath)(this.settings.tripsFolder);
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder || !(folder instanceof import_obsidian3.TFolder)) {
      return result;
    }
    const files = this.getAllMarkdownFiles(folder);
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      if (((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.type) === FRONTMATTER_TYPE && cache.frontmatter.trip) {
        result.set(cache.frontmatter.trip, file.path);
      }
    }
    return result;
  }
  getAllMarkdownFiles(folder) {
    const files = [];
    for (const child of folder.children) {
      if (child instanceof import_obsidian3.TFile && child.extension === "md") {
        files.push(child);
      } else if (child instanceof import_obsidian3.TFolder) {
        files.push(...this.getAllMarkdownFiles(child));
      }
    }
    return files;
  }
  /**
   * Write a trip note to the vault. If an existing synced file exists, overwrite it.
   * Otherwise create in the trips folder (inside a trip subfolder if one exists).
   */
  async writeTripNote(tripName, filename, content, existingPath) {
    if (existingPath) {
      const file = this.app.vault.getAbstractFileByPath(existingPath);
      if (file instanceof import_obsidian3.TFile) {
        await this.app.vault.modify(file, content);
        return;
      }
    }
    const basePath = (0, import_obsidian3.normalizePath)(this.settings.tripsFolder);
    const baseFolder = this.app.vault.getAbstractFileByPath(basePath);
    let targetFolder = basePath;
    if (baseFolder instanceof import_obsidian3.TFolder) {
      for (const child of baseFolder.children) {
        if (child instanceof import_obsidian3.TFolder && child.name.toLowerCase().includes(tripName.toLowerCase())) {
          targetFolder = child.path;
          break;
        }
      }
    }
    const filePath = (0, import_obsidian3.normalizePath)(`${targetFolder}/${filename}`);
    const parentPath = filePath.substring(0, filePath.lastIndexOf("/"));
    if (parentPath && !this.app.vault.getAbstractFileByPath(parentPath)) {
      await this.app.vault.createFolder(parentPath);
    }
    await this.app.vault.create(filePath, content);
  }
};

// main.ts
var TravelSyncPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new TravelSyncSettingTab(this.app, this));
    this.addCommand({
      id: "sync-trips",
      name: "Sync Trips",
      callback: () => this.runSync()
    });
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.apiUrl) {
        this.runSync();
      }
    });
  }
  async runSync() {
    const sync = new TravelSync(this.app, this.settings);
    await sync.syncTrips();
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
