name = "travel-app"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_API_URL = "https://cb554i1002.execute-api.us-east-1.amazonaws.com"
NEXT_PUBLIC_COGNITO_USER_POOL_ID = "us-east-1_qxqal14Wh"
NEXT_PUBLIC_COGNITO_CLIENT_ID = "1hl8rcqcmgmmknkunrdps06l8b"
NEXT_PUBLIC_COGNITO_REGION = "us-east-1"
